# Generated by Django 5.1.3 on 2024-12-01 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_alter_patient_patient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('pill_after_breakfast', models.BooleanField(default=False)),
                ('pill_after_lunch', models.BooleanField(default=False)),
                ('pill_after_dinner', models.BooleanField(default=False)),
                ('pill_at_bedtime', models.BooleanField(default=False)),
                ('pill_before_breakfast', models.BooleanField(default=False)),
                ('pill_before_dinner', models.BooleanField(default=False)),
                ('burning_degree', models.IntegerField(blank=True, null=True)),
                ('sourness_degree', models.IntegerField(blank=True, null=True)),
                ('burning_degree_morning', models.IntegerField(blank=True, null=True)),
                ('sourness_degree_morning', models.IntegerField(blank=True, null=True)),
                ('aluminum_tablets', models.IntegerField(blank=True, null=True)),
                ('other_pills', models.TextField(blank=True, null=True)),
                ('side_effects', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
