# Generated by Django 5.1.3 on 2024-12-16 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_questionnaireresponse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionnaireresponse',
            unique_together={('patient', 'date')},
        ),
    ]
